channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=22.2.2
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.2.0
  - defusedxml==0.7.1
  - ipython==8.7.0
  - torch==1.13.0
  - torchvision==0.14.0
name: mlflow-env
